### ISSUE TITLE
publish to pypi when ci passes

### ISSUE THREAD

**Issue by torrmal** [mindsdb/mindsdb_server#32]
when merge to master:

- when passes CI publish to pypi

**Comment by George3d6** [comment]
@torrmal  this should be already happening, however, since we push all changes to master, I've made it such that only the `release` branch will publish to `pypi`, so just merge the changes you want there and they should get published.

I can switch the publishing from release to master, but then we have to start using the branch + PR based approach.

**Comment by George3d6** [comment]
This is being done now, should have been closed.
